#use_frameworks!

platform :ios, '8.0'

target 'AWSS3ForDNSPathStyle_Example' do
  pod 'AWSS3ForDNSPathStyle', :path => '../'

  target 'AWSS3ForDNSPathStyle_Tests' do
    inherit! :search_paths

    
  end
end
